# Site settings
title: Your Name
description: > # this means to ignore newlines until "baseurl:"
  Your Description

# Build settings
markdown: kramdown
sass:
  style: compressed
compress_html:
  clippings: [html, head, title, meta, link, body, main, aside, script, div, span]
  comments: all
  profile: false

# Theme settings
theme: solarized

base-font-size: 16px
base-font: "Menlo, Consolas, monospace"
base-line-height: 25px

count-width: 60px
count-font-size: 14px
count-padding-left: 10px
code-padding-left: 10px

code-indent: 40px
code-indent-line-width: 1px

gutter-width: 2px
